[project]
name = "vocab-filter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "glossbert>=1.0.6",
    "idiomatch>=0.2.14",
    "lemminflect>=0.2.3",
    "nltk>=3.10.3",
    "sentence-transformers>=6.0.0",
    "simalign>=0.4",
    "wn>=1.1.1",
    "wordfreq>=3.1.1",
    "torch",
    "en-core-web-sm",
]

[tool.uv.sources]
torch = { index = "pytorch-cu124" }
en-core-web-sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl" }

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true
